### ISSUE TITLE
Improper data stored in a column

### ISSUE THREAD

**Issue by toileto** [Logee-Data/logee-dwh#11]
## Table name

`lgd_service_fee_pip`

## Column

`weight_metrics`

## Problems

<img width="211" alt="Screen Shot 2022-06-16 at 17 00 09" src="https://user-images.githubusercontent.com/33114786/174110781-97f715aa-2a83-46e6-b24a-2911399f8c72.png">

If I recall correctly, `weight_metrics` column is a column we propose to tackle unclear information regarding weight. Recently I checked it's becoming not hygiene - column is filled with unintended values.

**Comment by fikrihaykal41** [comment]
okay, I'll ask to change it to team BE
